version: '3'

# list of each "service": an individual part of the pipeline
services:

    mongodb:
      image: mongo
      ports:
      - 27017:27017
  
    tweet_collector:
      build: tweet_collector/
      volumes:
      - ./tweet_collector/:/app
      depends_on:
      - mongodb
    
    postgresdb:
        image: postgres
        ports:
        - "5555:5432"
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=3456
        - POSTGRES_DB=postgresdb
        

    etl_job:
       build: etl_job/
       volumes:
       - ./etl_job/:/app
       depends_on:
       - mongodb
       - postgresdb

    slackbot_lili:
       build: slackbot/
       volumes:
       - ./slackbot/:/app
       depends_on:
       - postgresdb

        # volumes:
        #     - ./tweetsdb:/var/lib/postgresql/data