version: '3'

# list of each "service": an individual part of the pipeline
services:
    tweets_collector:
        build: stream_tweet/
        volumes: 
        - ./stream_tweet/:/app
          
        depends_on: 
        - tweetsdb
    tweetsdb:
        image: postgres
        ports:
        - 5559:5432
        environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=2345
        # volumes:
        #     - ./tweetsdb:/var/lib/postgresql/data
    
        